@startuml
skinparam linetype polyline
skinparam linetype ortho
User -> MdfToFabric : pass required arguments
MdfToFabric -> MappingDataFlowToFabricNoteBook : call function to generate spark code
MappingDataFlowToFabricNoteBook -> ADFRestGetSource :  get mapping data flow script code using rest
ADFRestGetSource --> MappingDataFlowToFabricNoteBook : returns MappingDataFlowScriptCode
MappingDataFlowToFabricNoteBook -> OpenAISparkCodeGenerator : call OpenAI to generate spark code
OpenAISparkCodeGenerator --> MappingDataFlowToFabricNoteBook : returns SparkCode
MappingDataFlowToFabricNoteBook --> MdfToFabric : returns spark code
MdfToFabric -> MappingDataFlowToFabricNoteBook: call helper function to write spark code to Notebook
MappingDataFlowToFabricNoteBook -> PySparkNotebookWriter : write SparkCode to Fabric Notebook
MdfToFabric -> PySparkFileWriter : write SparkCode to  pyspark file
@enduml